version: 2

# Configuration with concurrent jobs!

jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install # Build
      - run: npm run test # Test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
